version: '3'

services:
  app:
    build: .
    container_name: app
    depends_on:
      - redis
      - database
    ports:
      - "${APP_PORT}:${APP_PORT}"
    command: yarn dev
    links:
      - redis
  database:
    image: mongo
    container_name: database
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "${DB_PORT}:${DB_PORT}"
  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - ${REDIS_PORT}
